import { db, firebaseReady } from "./firebase-config.js";
import { collection, addDoc, serverTimestamp, onSnapshot } from "https://www.gstatic.com/firebasejs/10.14.0/firebase-firestore.js";

const places = [
  {id:"petra", category:"historic", name:{ar:"البتراء",en:"Petra",fr:"Pétra",es:"Petra",de:"Petra",tr:"Petra",it:"Petra",ru:"Петра",zh:"佩特拉",ja:"ペトラ",ko:"페트라"}, area:{ar:"المدينة الوردية",en:"The Rose City",fr:"La ville rose",es:"La Ciudad Rosa",de:"Die Rosenstadt",tr:"Gül Şehri",it:"La Città Rosa",ru:"Розовый город",zh:"玫瑰之城",ja:"バラ色の都市",ko:"장미의 도시"}, rating:"4.9", time:{ar:"3 ساعات",en:"3 hours",fr:"3 heures",es:"3 horas",de:"3 Stunden",tr:"3 saat",it:"3 ore",ru:"3 часа",zh:"3小时",ja:"3時間",ko:"3시간"}, distance:"250 km", image:"https://www.bing.com/th/id/OIP.s5srCLhX6nf2EFfG42UxqwHaDg?w=193&h=135&c=8&rs=1&qlt=90&o=6&dpr=1.4&pid=ImgAns&rm=2", videos:["ap9MBTrJlNs","hyhtb8BOgug"] },
  {id:"wadi-rum", category:"nature", name:{ar:"وادي رم",en:"Wadi Rum",fr:"Wadi Rum",es:"Wadi Rum",de:"Wadi Rum",tr:"Wadi Rum",it:"Wadi Rum",ru:"Вади-Рам",zh:"瓦迪拉姆",ja:"ワディ・ラム",ko:"와디 럼"}, area:{ar:"وادي القمر",en:"Valley of the Moon",fr:"Vallée de la Lune",es:"Valle de la Luna",de:"Tal des Mondes",tr:"Ay Vadisi",it:"Valle della Luna",ru:"Долина Луны",zh:"月亮谷",ja:"月の谷",ko:"달의 계곡"}, rating:"4.8", time:{ar:"3.5 ساعة",en:"3.5 hours",fr:"3,5 heures",es:"3,5 horas",de:"3,5 Stunden",tr:"3,5 saat",it:"3,5 ore",ru:"3,5 часа",zh:"3.5小时",ja:"3.5時間",ko:"3.5시간"}, distance:"320 km", image:"https://alghad.com/Content/Upload/Large/42024694334445074919.jpg", videos:["VHKsJLuGaps","NOc9BPrvfIQ"] },
  {id:"jerash", category:"historic", name:{ar:"جرش",en:"Jerash",fr:"Gérasa",es:"Jerash",de:"Jerash",tr:"Jerash",it:"Jerash",ru:"Джераш",zh:"杰拉什",ja:"ジェラシュ",ko:"제라시"}, area:{ar:"روما الشرق",en:"Rome of the East",fr:"La Rome de l'Est",es:"La Roma de Oriente",de:"Rom des Ostens",tr:"Doğu'nun Roma'sı",it:"Roma d'Oriente",ru:"Рим Востока",zh:"东方罗马",ja:"東のローマ",ko:"동방의 로마"}, rating:"4.7", time:{ar:"45 دقيقة",en:"45 minutes",fr:"45 min",es:"45 min",de:"45 Minuten",tr:"45 dakika",it:"45 minuti",ru:"45 минут",zh:"45分钟",ja:"45分",ko:"45분"}, distance:"50 km", image:"https://www.bing.com/th/id/OIP.b_cTn-P9qvYiMvmox0X32AHaFj?w=193&h=145&c=8&rs=1&qlt=90&o=6&dpr=1.4&pid=ImgAns&rm=2", videos:["max2elkTKUc"] },
  {id:"dead-sea", category:"nature", name:{ar:"البحر الميت",en:"Dead Sea",fr:"Mer Morte",es:"Mar Muerto",de:"Totes Meer",tr:"Ölü Deniz",it:"Mar Morto",ru:"Мёртвое море",zh:"死海",ja:"死海",ko:"사해"}, area:{ar:"أخفض نقطة على الأرض",en:"Lowest point on Earth",fr:"Le point le plus bas de la Terre",es:"El punto más bajo de la Tierra",de:"Tiefster Punkt der Erde",tr:"Dünyanın en alçak noktası",it:"Il punto più basso della Terra",ru:"Самая низкая точка Земли",zh:"地球最低点",ja:"地球上で最も低い地点",ko:"지구에서 가장 낮은 지점"}, rating:"4.6", time:{ar:"50 دقيقة",en:"50 minutes",fr:"50 min",es:"50 min",de:"50 Minuten",tr:"50 dakika",it:"50 minuti",ru:"50 минут",zh:"50分钟",ja:"50分",ko:"50분"}, distance:"60 km", image:"https://www.bing.com/th/id/OIP.U1YbGQL9vDl7NAsIopp94AHaE7?w=193&h=135&c=8&rs=1&qlt=90&o=6&dpr=1.4&pid=ImgAns&rm=2", videos:["YnXa0GYH27c"] },
  {id:"ajloun", category:"historic", name:{ar:"عجلون",en:"Ajloun",fr:"Ajloun",es:"Ajloun",de:"Ajloun",tr:"Ajloun",it:"Ajloun",ru:"Аджлун",zh:"阿杰隆",ja:"アジュルン",ko:"아즐룬"}, area:{ar:"قلعة عجلون",en:"Ajloun Castle",fr:"Château d'Ajloun",es:"Castillo de Ajloun",de:"Burg Ajloun",tr:"Ajloun Kalesi",it:"Castello di Ajloun",ru:"Замок Аджлун",zh:"阿杰隆城堡",ja:"アジュルン城",ko:"아즐룬 성"}, rating:"4.5", time:{ar:"60 دقيقة",en:"60 minutes",fr:"60 min",es:"60 min",de:"60 Minuten",tr:"60 dakika",it:"60 minuti",ru:"60 минут",zh:"60分钟",ja:"60分",ko:"60분"}, distance:"70 km", image:"https://www.bing.com/th/id/OIP.P0OwedVNkP41w1c5ONDLdwHaFj?w=193&h=145&c=8&rs=1&qlt=90&o=6&dpr=1.4&pid=ImgAns&rm=2", videos:["KHuEqEM--Jk","Wsx6dng0Vjg"] }
];

const T = {
ar:{dir:"rtl",brand:"دِلني",splashText:"اكتشف المكان،<br>افهم قصته،<br><strong>وخلي الطريق أوضح.</strong>",start:"ابدأ",discoverJordan:"اكتشف الأردن",onboardingTitle:"استكشف تاريخ الأردن",onboardingText:"دِلني يصحبك في رحلة عبر المواقع الأثرية والسياحية الأردنية بمعلومات تاريخية غنية في كل خطوة.",next:"التالي ←",skip:"تخطي",technology:"التقنية",glassesIntro:"نظارة ذكية للسياحة والملاحة، مع GPS وBluetooth وتجربة صوتية تساعدك على اكتشاف المكان بدون تشتيت.",welcome:"أهلاً بك في دِلني",profileSub:"خلينا نتعرف عليك",profileQuote:"«خلينا نتعرف عليك حتى نجهز لك تجربة سياحة تناسبك»",nameLabel:"الاسم",namePlaceholder:"أدخل اسمك",ageLabel:"العمر",agePlaceholder:"أدخل عمرك",genderLabel:"الجنس",male:"ذكر",female:"أنثى",private:"لا أفصح",languageLabel:"اللغة المفضلة",continue:"متابعة ←",hello:"مرحباً",welcomeJordan:"مرحباً بك في الأردن",currentPlace:"البتراء، محافظة معان",startTrip:"ابدأ رحلتك",emergency:"طوارئ",glasses:"النظارة",nearby:"قريب منك",nearbyShort:"قريب",map:"الخريطة",featured:"مواقع مميزة",viewAll:"عرض الكل",home:"الرئيسية",explore:"استكشف",settings:"الإعدادات",emergencyTitle:"طوارئ 911",currentLocation:"موقعك الحالي",sendHelp:"إرسال المساعدة إلى 911",currentLocationDesc:"سيتم مشاركة موقعك الحالي مع خدمات الطوارئ عند الاتصال.",emergencyNotice:"تأكد من أن لديك حالة طارئة قبل الاتصال.",callNow:"اتصل الآن",exploreJordan:"استكشف الأردن",yourLocation:"موقعك",historic:"أثري",tourist:"موقع سياحي",nature:"طبيعي",fun:"ترفيهي",choosePlace:"اختر موقعاً لبدء الرحلة",smartNavigation:"النظارة الذكية للملاحة",demoConnected:"وضع العرض — جاهزة للربط",bluetoothHint:"يمكنك محاولة الربط عبر Bluetooth إذا كان جهازك والمتصفح يدعمان Web Bluetooth.",connect:"ربط النظارة",battery:"البطارية",locateMe:"حدد موقعي",locateDesc:"GPS من الهاتف",voiceGuide:"تجربة التوجيه الصوتي",voiceDesc:"تشغيل إرشاد تجريبي",specs:"المواصفات",lenses:"عدسات",dual:"مزدوجة — يمين ويسار",independent:"مستقل ✓",runtime:"التشغيل",hours:"ساعة",weight:"الوزن",nearbyPlaces:"المواقع القريبة",all:"الكل",glassesGps:"النظارة GPS",glassesStatus:"حالة النظارة",languageSetting:"اللغة",notifications:"الإشعارات",guidanceMode:"وضع التوجيه",active:"نشط",shareLocation:"مشاركة الموقع",emergencyAccess:"الوصول السريع للطوارئ",areaVideos:"🎥 فيديوهات المنطقة",saved:"تم حفظ بياناتك ✓",savedLocal:"تم حفظ البيانات محلياً",connected:"تم ربط النظارة ✓",bluetoothUnavailable:"Bluetooth غير متاح في هذا المتصفح، تم تفعيل وضع العرض.",locationFound:"تم تحديد موقعك",locationDenied:"تعذر الوصول إلى موقعك",voiceStarted:"بدأ التوجيه الصوتي التجريبي",video:"فيديو",openYoutube:"فتح الفيديو على YouTube ↗"},
en:{dir:"ltr",brand:"Daleel",splashText:"Discover the place,<br>understand its story,<br><strong>and make the journey clearer.</strong>",start:"Start",discoverJordan:"Discover Jordan",onboardingTitle:"Explore Jordan's history",onboardingText:"Daleel guides you through Jordanian heritage and tourist sites with rich information at every step.",next:"Next →",skip:"Skip",technology:"Technology",glassesIntro:"Smart glasses for tourism and navigation, with GPS, Bluetooth and audio guidance to help you explore hands-free.",welcome:"Welcome to Daleel",profileSub:"Let's get to know you",profileQuote:"“Tell us a little about you so we can tailor your travel experience.”",nameLabel:"Name",namePlaceholder:"Enter your name",ageLabel:"Age",agePlaceholder:"Enter your age",genderLabel:"Gender",male:"Male",female:"Female",private:"Prefer not to say",languageLabel:"Preferred language",continue:"Continue →",hello:"Hello",welcomeJordan:"Welcome to Jordan",currentPlace:"Petra, Ma'an Governorate",startTrip:"Start your trip",emergency:"Emergency",glasses:"Glasses",nearby:"Nearby",nearbyShort:"Nearby",map:"Map",featured:"Featured places",viewAll:"View all",home:"Home",explore:"Explore",settings:"Settings",emergencyTitle:"911 Emergency",currentLocation:"Your current location",sendHelp:"Send help to 911",currentLocationDesc:"Your current location may be shared with emergency services when you call.",emergencyNotice:"Make sure you have a genuine emergency before calling.",callNow:"Call now",exploreJordan:"Explore Jordan",yourLocation:"Your location",historic:"Historic",tourist:"Tourist site",nature:"Nature",fun:"Entertainment",choosePlace:"Choose a place to start your trip",smartNavigation:"Smart navigation glasses",demoConnected:"Demo mode — ready to connect",bluetoothHint:"Try Bluetooth pairing if your device and browser support Web Bluetooth.",connect:"Connect glasses",battery:"Battery",locateMe:"Locate me",locateDesc:"Phone GPS",voiceGuide:"Try voice guidance",voiceDesc:"Play a demo instruction",specs:"Specifications",lenses:"Lenses",dual:"Dual — left & right",independent:"Independent ✓",runtime:"Runtime",hours:"hours",weight:"Weight",nearbyPlaces:"Nearby places",all:"All",glassesGps:"Glasses GPS",glassesStatus:"Glasses status",languageSetting:"Language",notifications:"Notifications",guidanceMode:"Guidance mode",active:"Active",shareLocation:"Share location",emergencyAccess:"Quick emergency access",areaVideos:"🎥 Area videos",saved:"Your data was saved ✓",savedLocal:"Saved locally",connected:"Glasses connected ✓",bluetoothUnavailable:"Bluetooth is unavailable in this browser; demo mode is enabled.",locationFound:"Location found",locationDenied:"Could not access your location",voiceStarted:"Demo voice guidance started",video:"Video",openYoutube:"Open on YouTube ↗"},
fr:{dir:"ltr",brand:"Daleel",splashText:"Découvrez le lieu,<br>comprenez son histoire,<br><strong>et rendez le voyage plus clair.</strong>",start:"Commencer",discoverJordan:"Découvrez la Jordanie",onboardingTitle:"Explorez l'histoire de la Jordanie",onboardingText:"Daleel vous accompagne dans les sites historiques et touristiques de Jordanie.",next:"Suivant →",skip:"Passer",technology:"Technologie",glassesIntro:"Lunettes intelligentes pour le tourisme et la navigation, avec GPS, Bluetooth et guidage audio.",welcome:"Bienvenue sur Daleel",profileSub:"Faisons connaissance",profileQuote:"« Parlez-nous de vous pour personnaliser votre expérience. »",nameLabel:"Nom",namePlaceholder:"Entrez votre nom",ageLabel:"Âge",agePlaceholder:"Entrez votre âge",genderLabel:"Genre",male:"Homme",female:"Femme",private:"Je préfère ne pas répondre",languageLabel:"Langue préférée",continue:"Continuer →",hello:"Bonjour",welcomeJordan:"Bienvenue en Jordanie",currentPlace:"Pétra, gouvernorat de Ma'an",startTrip:"Commencer le voyage",emergency:"Urgence",glasses:"Lunettes",nearby:"À proximité",nearbyShort:"Près",map:"Carte",featured:"Lieux recommandés",viewAll:"Tout voir",home:"Accueil",explore:"Explorer",settings:"Paramètres",emergencyTitle:"Urgence 911",currentLocation:"Votre position actuelle",sendHelp:"Envoyer de l'aide au 911",currentLocationDesc:"Votre position peut être partagée avec les services d'urgence lors de l'appel.",emergencyNotice:"Assurez-vous d'avoir une véritable urgence avant d'appeler.",callNow:"Appeler maintenant",exploreJordan:"Explorer la Jordanie",yourLocation:"Votre position",historic:"Historique",tourist:"Site touristique",nature:"Nature",fun:"Loisirs",choosePlace:"Choisissez un lieu pour commencer",smartNavigation:"Lunettes de navigation",demoConnected:"Mode démo — prête à connecter",bluetoothHint:"Essayez le Bluetooth si votre appareil et votre navigateur le prennent en charge.",connect:"Connecter",battery:"Batterie",locateMe:"Me localiser",locateDesc:"GPS du téléphone",voiceGuide:"Guidage vocal",voiceDesc:"Lire une instruction de démonstration",specs:"Spécifications",lenses:"Verres",dual:"Doubles — gauche et droite",independent:"Indépendant ✓",runtime:"Autonomie",hours:"heures",weight:"Poids",nearbyPlaces:"Lieux à proximité",all:"Tous",glassesGps:"GPS des lunettes",glassesStatus:"État des lunettes",languageSetting:"Langue",notifications:"Notifications",guidanceMode:"Mode guidage",active:"Actif",shareLocation:"Partager la position",emergencyAccess:"Accès rapide aux urgences",areaVideos:"🎥 Vidéos de la région",saved:"Données enregistrées ✓",savedLocal:"Enregistré localement",connected:"Lunettes connectées ✓",bluetoothUnavailable:"Bluetooth indisponible dans ce navigateur ; mode démo activé.",locationFound:"Position trouvée",locationDenied:"Position inaccessible",voiceStarted:"Guidage vocal de démonstration démarré",video:"Vidéo",openYoutube:"Ouvrir sur YouTube ↗"},
es:{dir:"ltr",brand:"Daleel",splashText:"Descubre el lugar,<br>entiende su historia,<br><strong>y haz el camino más claro.</strong>",start:"Empezar",discoverJordan:"Descubre Jordania",onboardingTitle:"Explora la historia de Jordania",onboardingText:"Daleel te acompaña por los lugares históricos y turísticos de Jordania.",next:"Siguiente →",skip:"Omitir",technology:"Tecnología",glassesIntro:"Gafas inteligentes para turismo y navegación, con GPS, Bluetooth y guía por voz.",welcome:"Bienvenido a Daleel",profileSub:"Conozcámonos",profileQuote:"«Cuéntanos sobre ti para adaptar tu experiencia de viaje.»",nameLabel:"Nombre",namePlaceholder:"Introduce tu nombre",ageLabel:"Edad",agePlaceholder:"Introduce tu edad",genderLabel:"Género",male:"Hombre",female:"Mujer",private:"Prefiero no decirlo",languageLabel:"Idioma preferido",continue:"Continuar →",hello:"Hola",welcomeJordan:"Bienvenido a Jordania",currentPlace:"Petra, gobernación de Ma'an",startTrip:"Comenzar viaje",emergency:"Emergencia",glasses:"Gafas",nearby:"Cerca",nearbyShort:"Cerca",map:"Mapa",featured:"Lugares destacados",viewAll:"Ver todo",home:"Inicio",explore:"Explorar",settings:"Ajustes",emergencyTitle:"Emergencia 911",currentLocation:"Tu ubicación actual",sendHelp:"Enviar ayuda al 911",currentLocationDesc:"Tu ubicación puede compartirse con emergencias al llamar.",emergencyNotice:"Asegúrate de que sea una emergencia real antes de llamar.",callNow:"Llamar ahora",exploreJordan:"Explora Jordania",yourLocation:"Tu ubicación",historic:"Histórico",tourist:"Lugar turístico",nature:"Naturaleza",fun:"Ocio",choosePlace:"Elige un lugar para comenzar",smartNavigation:"Gafas de navegación",demoConnected:"Modo demo — lista para conectar",bluetoothHint:"Prueba Bluetooth si tu dispositivo y navegador son compatibles.",connect:"Conectar gafas",battery:"Batería",locateMe:"Localizarme",locateDesc:"GPS del teléfono",voiceGuide:"Guía por voz",voiceDesc:"Reproducir una indicación de prueba",specs:"Especificaciones",lenses:"Lentes",dual:"Dobles — izquierda y derecha",independent:"Independiente ✓",runtime:"Autonomía",hours:"horas",weight:"Peso",nearbyPlaces:"Lugares cercanos",all:"Todos",glassesGps:"GPS de las gafas",glassesStatus:"Estado de las gafas",languageSetting:"Idioma",notifications:"Notificaciones",guidanceMode:"Modo de guía",active:"Activo",shareLocation:"Compartir ubicación",emergencyAccess:"Acceso rápido a emergencias",areaVideos:"🎥 Vídeos de la zona",saved:"Datos guardados ✓",savedLocal:"Guardado localmente",connected:"Gafas conectadas ✓",bluetoothUnavailable:"Bluetooth no está disponible; se activó el modo demo.",locationFound:"Ubicación encontrada",locationDenied:"No se pudo acceder a la ubicación",voiceStarted:"Guía de voz de demostración iniciada",video:"Vídeo",openYoutube:"Abrir en YouTube ↗"},
de:{dir:"ltr",brand:"Daleel",splashText:"Entdecke den Ort,<br>verstehe seine Geschichte,<br><strong>und mach den Weg klarer.</strong>",start:"Start",discoverJordan:"Jordanien entdecken",onboardingTitle:"Jordaniens Geschichte entdecken",onboardingText:"Daleel begleitet dich zu historischen und touristischen Orten in Jordanien.",next:"Weiter →",skip:"Überspringen",technology:"Technologie",glassesIntro:"Smarte Brille für Tourismus und Navigation mit GPS, Bluetooth und Sprachführung.",welcome:"Willkommen bei Daleel",profileSub:"Lernen wir uns kennen",profileQuote:"„Erzähl uns etwas über dich, damit wir deine Reise anpassen können.“",nameLabel:"Name",namePlaceholder:"Name eingeben",ageLabel:"Alter",agePlaceholder:"Alter eingeben",genderLabel:"Geschlecht",male:"Männlich",female:"Weiblich",private:"Keine Angabe",languageLabel:"Bevorzugte Sprache",continue:"Weiter →",hello:"Hallo",welcomeJordan:"Willkommen in Jordanien",currentPlace:"Petra, Gouvernement Ma'an",startTrip:"Reise starten",emergency:"Notfall",glasses:"Brille",nearby:"In der Nähe",nearbyShort:"Nähe",map:"Karte",featured:"Empfohlene Orte",viewAll:"Alle anzeigen",home:"Startseite",explore:"Entdecken",settings:"Einstellungen",emergencyTitle:"Notruf 911",currentLocation:"Dein aktueller Standort",sendHelp:"Hilfe an 911 senden",currentLocationDesc:"Dein Standort kann beim Anruf an den Notdienst übermittelt werden.",emergencyNotice:"Rufe nur bei einem echten Notfall an.",callNow:"Jetzt anrufen",exploreJordan:"Jordanien entdecken",yourLocation:"Dein Standort",historic:"Historisch",tourist:"Touristenort",nature:"Natur",fun:"Freizeit",choosePlace:"Ort für die Reise auswählen",smartNavigation:"Smarte Navigationsbrille",demoConnected:"Demo-Modus — bereit zum Verbinden",bluetoothHint:"Bluetooth ist möglich, wenn Gerät und Browser Web Bluetooth unterstützen.",connect:"Brille verbinden",battery:"Akku",locateMe:"Standort ermitteln",locateDesc:"Telefon-GPS",voiceGuide:"Sprachführung testen",voiceDesc:"Testansage abspielen",specs:"Spezifikationen",lenses:"Gläser",dual:"Doppelt — links & rechts",independent:"Unabhängig ✓",runtime:"Laufzeit",hours:"Stunden",weight:"Gewicht",nearbyPlaces:"Orte in der Nähe",all:"Alle",glassesGps:"Brillen-GPS",glassesStatus:"Brillenstatus",languageSetting:"Sprache",notifications:"Benachrichtigungen",guidanceMode:"Navigationsmodus",active:"Aktiv",shareLocation:"Standort teilen",emergencyAccess:"Schneller Notrufzugriff",areaVideos:"🎥 Videos der Region",saved:"Daten gespeichert ✓",savedLocal:"Lokal gespeichert",connected:"Brille verbunden ✓",bluetoothUnavailable:"Bluetooth ist in diesem Browser nicht verfügbar; Demo-Modus aktiviert.",locationFound:"Standort gefunden",locationDenied:"Standortzugriff fehlgeschlagen",voiceStarted:"Demo-Sprachführung gestartet",video:"Video",openYoutube:"Auf YouTube öffnen ↗"},
tr:{dir:"ltr",brand:"Daleel",splashText:"Yeri keşfet,<br>hikâyesini öğren,<br><strong>yolu daha anlaşılır kıl.</strong>",start:"Başla",discoverJordan:"Ürdün'ü keşfet",onboardingTitle:"Ürdün tarihini keşfet",onboardingText:"Daleel, Ürdün'ün tarihi ve turistik yerlerinde sana eşlik eder.",next:"İleri →",skip:"Atla",technology:"Teknoloji",glassesIntro:"GPS, Bluetooth ve sesli yönlendirmeli akıllı turizm ve navigasyon gözlüğü.",welcome:"Daleel'e hoş geldin",profileSub:"Seni tanıyalım",profileQuote:"“Seyahat deneyimini sana göre hazırlayabilmemiz için bize biraz kendinden bahset.”",nameLabel:"Ad",namePlaceholder:"Adını gir",ageLabel:"Yaş",agePlaceholder:"Yaşını gir",genderLabel:"Cinsiyet",male:"Erkek",female:"Kadın",private:"Belirtmek istemiyorum",languageLabel:"Tercih edilen dil",continue:"Devam →",hello:"Merhaba",welcomeJordan:"Ürdün'e hoş geldin",currentPlace:"Petra, Ma'an",startTrip:"Yolculuğu başlat",emergency:"Acil",glasses:"Gözlük",nearby:"Yakında",nearbyShort:"Yakın",map:"Harita",featured:"Öne çıkan yerler",viewAll:"Tümünü gör",home:"Ana sayfa",explore:"Keşfet",settings:"Ayarlar",emergencyTitle:"911 Acil",currentLocation:"Mevcut konumun",sendHelp:"911'e yardım çağır",currentLocationDesc:"Arama sırasında konumun acil servislere paylaşılabilir.",emergencyNotice:"Aramadan önce gerçek bir acil durum olduğundan emin ol.",callNow:"Şimdi ara",exploreJordan:"Ürdün'ü keşfet",yourLocation:"Konumun",historic:"Tarihi",tourist:"Turistik",nature:"Doğa",fun:"Eğlence",choosePlace:"Yolculuk için bir yer seç",smartNavigation:"Akıllı navigasyon gözlüğü",demoConnected:"Demo modu — bağlanmaya hazır",bluetoothHint:"Cihazın ve tarayıcın Web Bluetooth destekliyorsa Bluetooth bağlantısını dene.",connect:"Gözlüğü bağla",battery:"Pil",locateMe:"Konumumu bul",locateDesc:"Telefon GPS'i",voiceGuide:"Sesli yönlendirmeyi dene",voiceDesc:"Demo yönlendirmesi",specs:"Özellikler",lenses:"Lensler",dual:"Çift — sağ ve sol",independent:"Bağımsız ✓",runtime:"Çalışma süresi",hours:"saat",weight:"Ağırlık",nearbyPlaces:"Yakındaki yerler",all:"Tümü",glassesGps:"Gözlük GPS",glassesStatus:"Gözlük durumu",languageSetting:"Dil",notifications:"Bildirimler",guidanceMode:"Yönlendirme modu",active:"Aktif",shareLocation:"Konumu paylaş",emergencyAccess:"Hızlı acil erişim",areaVideos:"🎥 Bölge videoları",saved:"Verilerin kaydedildi ✓",savedLocal:"Yerel kaydedildi",connected:"Gözlük bağlandı ✓",bluetoothUnavailable:"Bu tarayıcıda Bluetooth yok; demo modu etkin.",locationFound:"Konum bulundu",locationDenied:"Konuma erişilemedi",voiceStarted:"Demo sesli yönlendirme başladı",video:"Video",openYoutube:"YouTube'da aç ↗"},
it:{dir:"ltr",brand:"Daleel",splashText:"Scopri il luogo,<br>comprendi la sua storia,<br><strong>e rendi il viaggio più chiaro.</strong>",start:"Inizia",discoverJordan:"Scopri la Giordania",onboardingTitle:"Esplora la storia della Giordania",onboardingText:"Daleel ti accompagna tra siti storici e turistici della Giordania.",next:"Avanti →",skip:"Salta",technology:"Tecnologia",glassesIntro:"Occhiali intelligenti per turismo e navigazione con GPS, Bluetooth e guida vocale.",welcome:"Benvenuto su Daleel",profileSub:"Conosciamoci",profileQuote:"«Raccontaci qualcosa di te per personalizzare il viaggio.»",nameLabel:"Nome",namePlaceholder:"Inserisci il nome",ageLabel:"Età",agePlaceholder:"Inserisci l'età",genderLabel:"Genere",male:"Uomo",female:"Donna",private:"Preferisco non dirlo",languageLabel:"Lingua preferita",continue:"Continua →",hello:"Ciao",welcomeJordan:"Benvenuto in Giordania",currentPlace:"Petra, governatorato di Ma'an",startTrip:"Inizia viaggio",emergency:"Emergenza",glasses:"Occhiali",nearby:"Vicino",nearbyShort:"Vicino",map:"Mappa",featured:"Luoghi in evidenza",viewAll:"Vedi tutto",home:"Home",explore:"Esplora",settings:"Impostazioni",emergencyTitle:"Emergenza 911",currentLocation:"La tua posizione",sendHelp:"Invia aiuto al 911",currentLocationDesc:"La tua posizione può essere condivisa con i soccorsi durante la chiamata.",emergencyNotice:"Chiama solo in caso di vera emergenza.",callNow:"Chiama ora",exploreJordan:"Esplora la Giordania",yourLocation:"La tua posizione",historic:"Storico",tourist:"Turistico",nature:"Natura",fun:"Svago",choosePlace:"Scegli un luogo per iniziare",smartNavigation:"Occhiali per la navigazione",demoConnected:"Modalità demo — pronta al collegamento",bluetoothHint:"Prova il Bluetooth se dispositivo e browser supportano Web Bluetooth.",connect:"Collega occhiali",battery:"Batteria",locateMe:"Trova la mia posizione",locateDesc:"GPS del telefono",voiceGuide:"Prova guida vocale",voiceDesc:"Riproduci istruzione demo",specs:"Specifiche",lenses:"Lenti",dual:"Doppie — destra e sinistra",independent:"Indipendente ✓",runtime:"Autonomia",hours:"ore",weight:"Peso",nearbyPlaces:"Luoghi vicini",all:"Tutti",glassesGps:"GPS occhiali",glassesStatus:"Stato occhiali",languageSetting:"Lingua",notifications:"Notifiche",guidanceMode:"Modalità guida",active:"Attiva",shareLocation:"Condividi posizione",emergencyAccess:"Accesso rapido emergenza",areaVideos:"🎥 Video della zona",saved:"Dati salvati ✓",savedLocal:"Salvato localmente",connected:"Occhiali collegati ✓",bluetoothUnavailable:"Bluetooth non disponibile; modalità demo attivata.",locationFound:"Posizione trovata",locationDenied:"Impossibile accedere alla posizione",voiceStarted:"Guida vocale demo avviata",video:"Video",openYoutube:"Apri su YouTube ↗"},
ru:{dir:"ltr",brand:"Daleel",splashText:"Откройте место,<br>узнайте его историю,<br><strong>и сделайте путь понятнее.</strong>",start:"Начать",discoverJordan:"Откройте Иорданию",onboardingTitle:"Исследуйте историю Иордании",onboardingText:"Daleel сопровождает вас по историческим и туристическим местам Иордании.",next:"Далее →",skip:"Пропустить",technology:"Технологии",glassesIntro:"Умные очки для туризма и навигации с GPS, Bluetooth и голосовыми подсказками.",welcome:"Добро пожаловать в Daleel",profileSub:"Давайте познакомимся",profileQuote:"«Расскажите о себе, чтобы мы настроили путешествие.»",nameLabel:"Имя",namePlaceholder:"Введите имя",ageLabel:"Возраст",agePlaceholder:"Введите возраст",genderLabel:"Пол",male:"Мужчина",female:"Женщина",private:"Не хочу указывать",languageLabel:"Предпочтительный язык",continue:"Продолжить →",hello:"Здравствуйте",welcomeJordan:"Добро пожаловать в Иорданию",currentPlace:"Петра, провинция Маан",startTrip:"Начать маршрут",emergency:"Экстренная помощь",glasses:"Очки",nearby:"Рядом",nearbyShort:"Рядом",map:"Карта",featured:"Избранные места",viewAll:"Все",home:"Главная",explore:"Исследовать",settings:"Настройки",emergencyTitle:"Экстренный вызов 911",currentLocation:"Ваше местоположение",sendHelp:"Вызвать помощь 911",currentLocationDesc:"При звонке ваше местоположение может быть передано экстренным службам.",emergencyNotice:"Звоните только при настоящей чрезвычайной ситуации.",callNow:"Позвонить",exploreJordan:"Исследовать Иорданию",yourLocation:"Ваше местоположение",historic:"История",tourist:"Туризм",nature:"Природа",fun:"Развлечения",choosePlace:"Выберите место для маршрута",smartNavigation:"Умные навигационные очки",demoConnected:"Демо-режим — готово к подключению",bluetoothHint:"Попробуйте Bluetooth, если устройство и браузер поддерживают Web Bluetooth.",connect:"Подключить очки",battery:"Батарея",locateMe:"Определить меня",locateDesc:"GPS телефона",voiceGuide:"Голосовая навигация",voiceDesc:"Тестовая подсказка",specs:"Характеристики",lenses:"Линзы",dual:"Двойные — левая и правая",independent:"Независимый ✓",runtime:"Работа",hours:"часов",weight:"Вес",nearbyPlaces:"Места рядом",all:"Все",glassesGps:"GPS очков",glassesStatus:"Состояние очков",languageSetting:"Язык",notifications:"Уведомления",guidanceMode:"Режим навигации",active:"Активен",shareLocation:"Поделиться местоположением",emergencyAccess:"Быстрый доступ к экстренной помощи",areaVideos:"🎥 Видео района",saved:"Данные сохранены ✓",savedLocal:"Сохранено локально",connected:"Очки подключены ✓",bluetoothUnavailable:"Bluetooth недоступен; включён демо-режим.",locationFound:"Местоположение найдено",locationDenied:"Не удалось получить местоположение",voiceStarted:"Демо-голосовая навигация запущена",video:"Видео",openYoutube:"Открыть YouTube ↗"},
zh:{dir:"ltr",brand:"Daleel",splashText:"探索地点，<br>了解它的故事，<br><strong>让旅程更清晰。</strong>",start:"开始",discoverJordan:"探索约旦",onboardingTitle:"探索约旦历史",onboardingText:"Daleel 带你探索约旦的历史与旅游景点。",next:"下一步 →",skip:"跳过",technology:"科技",glassesIntro:"用于旅游和导航的智能眼镜，支持 GPS、蓝牙和语音引导。",welcome:"欢迎使用 Daleel",profileSub:"认识一下",profileQuote:"“告诉我们一些信息，为你定制旅行体验。”",nameLabel:"姓名",namePlaceholder:"输入姓名",ageLabel:"年龄",agePlaceholder:"输入年龄",genderLabel:"性别",male:"男",female:"女",private:"不愿透露",languageLabel:"首选语言",continue:"继续 →",hello:"你好",welcomeJordan:"欢迎来到约旦",currentPlace:"佩特拉，马安省",startTrip:"开始旅程",emergency:"紧急",glasses:"眼镜",nearby:"附近",nearbyShort:"附近",map:"地图",featured:"精选地点",viewAll:"查看全部",home:"首页",explore:"探索",settings:"设置",emergencyTitle:"911 紧急",currentLocation:"你的位置",sendHelp:"向 911 求助",currentLocationDesc:"拨打电话时，你的位置可能会与紧急服务共享。",emergencyNotice:"请确认是真正的紧急情况后再拨打。",callNow:"立即呼叫",exploreJordan:"探索约旦",yourLocation:"你的位置",historic:"历史",tourist:"旅游景点",nature:"自然",fun:"娱乐",choosePlace:"选择地点开始旅程",smartNavigation:"智能导航眼镜",demoConnected:"演示模式 — 等待连接",bluetoothHint:"如果设备和浏览器支持 Web Bluetooth，可尝试连接。",connect:"连接眼镜",battery:"电量",locateMe:"定位我",locateDesc:"手机 GPS",voiceGuide:"体验语音导航",voiceDesc:"播放演示提示",specs:"规格",lenses:"镜片",dual:"双镜片 — 左右",independent:"独立 ✓",runtime:"续航",hours:"小时",weight:"重量",nearbyPlaces:"附近地点",all:"全部",glassesGps:"眼镜 GPS",glassesStatus:"眼镜状态",languageSetting:"语言",notifications:"通知",guidanceMode:"导航模式",active:"已启用",shareLocation:"共享位置",emergencyAccess:"快速紧急入口",areaVideos:"🎥 地区视频",saved:"数据已保存 ✓",savedLocal:"已保存到本地",connected:"眼镜已连接 ✓",bluetoothUnavailable:"此浏览器不支持蓝牙，已启用演示模式。",locationFound:"已找到位置",locationDenied:"无法获取位置",voiceStarted:"演示语音导航已开始",video:"视频",openYoutube:"在 YouTube 打开 ↗"},
ja:{dir:"ltr",brand:"Daleel",splashText:"場所を発見し、<br>物語を知り、<br><strong>旅をもっと分かりやすく。</strong>",start:"開始",discoverJordan:"ヨルダンを発見",onboardingTitle:"ヨルダンの歴史を探る",onboardingText:"Daleel がヨルダンの歴史的・観光地をご案内します。",next:"次へ →",skip:"スキップ",technology:"テクノロジー",glassesIntro:"GPS、Bluetooth、音声案内を備えた観光・ナビゲーション用スマートグラス。",welcome:"Daleelへようこそ",profileSub:"あなたについて教えてください",profileQuote:"「旅行体験をあなたに合わせるため、少し教えてください。」",nameLabel:"名前",namePlaceholder:"名前を入力",ageLabel:"年齢",agePlaceholder:"年齢を入力",genderLabel:"性別",male:"男性",female:"女性",private:"回答しない",languageLabel:"希望言語",continue:"続ける →",hello:"こんにちは",welcomeJordan:"ヨルダンへようこそ",currentPlace:"ペトラ、マアーン県",startTrip:"旅を開始",emergency:"緊急",glasses:"グラス",nearby:"近く",nearbyShort:"近く",map:"地図",featured:"おすすめスポット",viewAll:"すべて見る",home:"ホーム",explore:"探索",settings:"設定",emergencyTitle:"911 緊急",currentLocation:"現在地",sendHelp:"911へ救助要請",currentLocationDesc:"通話時に現在地が緊急サービスへ共有される場合があります。",emergencyNotice:"本当の緊急時のみ電話してください。",callNow:"今すぐ電話",exploreJordan:"ヨルダンを探索",yourLocation:"現在地",historic:"史跡",tourist:"観光地",nature:"自然",fun:"レジャー",choosePlace:"場所を選んで旅を開始",smartNavigation:"スマートナビグラス",demoConnected:"デモモード — 接続準備完了",bluetoothHint:"端末とブラウザがWeb Bluetoothに対応していれば接続できます。",connect:"グラスを接続",battery:"バッテリー",locateMe:"現在地を取得",locateDesc:"スマホGPS",voiceGuide:"音声案内を試す",voiceDesc:"デモ案内を再生",specs:"仕様",lenses:"レンズ",dual:"デュアル — 左右",independent:"独立 ✓",runtime:"稼働時間",hours:"時間",weight:"重量",nearbyPlaces:"近くの場所",all:"すべて",glassesGps:"グラスGPS",glassesStatus:"グラス状態",languageSetting:"言語",notifications:"通知",guidanceMode:"案内モード",active:"有効",shareLocation:"位置情報を共有",emergencyAccess:"緊急アクセス",areaVideos:"🎥 エリア動画",saved:"データを保存しました ✓",savedLocal:"ローカルに保存しました",connected:"グラスが接続されました ✓",bluetoothUnavailable:"このブラウザではBluetoothを利用できません。デモモードを有効にしました。",locationFound:"現在地を取得しました",locationDenied:"位置情報にアクセスできません",voiceStarted:"デモ音声案内を開始しました",video:"動画",openYoutube:"YouTubeで開く ↗"},
ko:{dir:"ltr",brand:"Daleel",splashText:"장소를 발견하고,<br>이야기를 이해하고,<br><strong>길을 더 쉽게 만들어 보세요.</strong>",start:"시작",discoverJordan:"요르단 탐험",onboardingTitle:"요르단의 역사 탐험",onboardingText:"Daleel이 요르단의 역사·관광지를 안내합니다.",next:"다음 →",skip:"건너뛰기",technology:"기술",glassesIntro:"GPS, Bluetooth, 음성 안내를 갖춘 관광·내비게이션 스마트 글래스입니다.",welcome:"Daleel에 오신 것을 환영합니다",profileSub:"당신을 알아볼게요",profileQuote:"“맞춤 여행 경험을 위해 몇 가지 정보를 알려주세요.”",nameLabel:"이름",namePlaceholder:"이름 입력",ageLabel:"나이",agePlaceholder:"나이 입력",genderLabel:"성별",male:"남성",female:"여성",private:"공개하지 않음",languageLabel:"선호 언어",continue:"계속 →",hello:"안녕하세요",welcomeJordan:"요르단에 오신 것을 환영합니다",currentPlace:"페트라, 마안 주",startTrip:"여행 시작",emergency:"긴급",glasses:"글래스",nearby:"근처",nearbyShort:"근처",map:"지도",featured:"추천 장소",viewAll:"모두 보기",home:"홈",explore:"탐색",settings:"설정",emergencyTitle:"911 긴급",currentLocation:"현재 위치",sendHelp:"911에 도움 요청",currentLocationDesc:"통화 시 현재 위치가 긴급 서비스에 공유될 수 있습니다.",emergencyNotice:"실제 긴급 상황에서만 전화하세요.",callNow:"지금 전화",exploreJordan:"요르단 탐험",yourLocation:"내 위치",historic:"역사",tourist:"관광지",nature:"자연",fun:"여가",choosePlace:"여행할 장소 선택",smartNavigation:"스마트 내비게이션 글래스",demoConnected:"데모 모드 — 연결 준비됨",bluetoothHint:"기기와 브라우저가 Web Bluetooth를 지원하면 연결할 수 있습니다.",connect:"글래스 연결",battery:"배터리",locateMe:"내 위치 찾기",locateDesc:"휴대폰 GPS",voiceGuide:"음성 안내 체험",voiceDesc:"데모 안내 재생",specs:"사양",lenses:"렌즈",dual:"듀얼 — 좌우",independent:"독립 ✓",runtime:"사용 시간",hours:"시간",weight:"무게",nearbyPlaces:"주변 장소",all:"전체",glassesGps:"글래스 GPS",glassesStatus:"글래스 상태",languageSetting:"언어",notifications:"알림",guidanceMode:"안내 모드",active:"활성",shareLocation:"위치 공유",emergencyAccess:"긴급 빠른 접근",areaVideos:"🎥 지역 영상",saved:"데이터가 저장되었습니다 ✓",savedLocal:"로컬에 저장되었습니다",connected:"글래스가 연결되었습니다 ✓",bluetoothUnavailable:"이 브라우저에서는 Bluetooth를 사용할 수 없어 데모 모드를 켰습니다.",locationFound:"위치를 찾았습니다",locationDenied:"위치에 접근할 수 없습니다",voiceStarted:"데모 음성 안내를 시작했습니다",video:"영상",openYoutube:"YouTube에서 열기 ↗"}
};

let lang=localStorage.getItem("daleelLang")||"ar";
let selected={gender:"",language:lang};
let user=JSON.parse(localStorage.getItem("daleelUser")||"null");
let bluetoothDevice=null;
const $=s=>document.querySelector(s), $$=s=>document.querySelectorAll(s);
const tr=k=>T[lang]?.[k]??T.ar[k]??k;
const placeText=(p,key)=>p[key]?.[lang]??p[key]?.en??"";

function applyLanguage(){
  const t=T[lang]||T.ar;
  document.documentElement.lang=lang; document.documentElement.dir=t.dir;
  $$("[data-i18n]").forEach(el=>{ const key=el.dataset.i18n; if(t[key]!==undefined) el.innerHTML=t[key]; });
  $$("[data-i18n-placeholder]").forEach(el=>{el.placeholder=t[el.dataset.i18nPlaceholder]||el.placeholder});
  if($("#language"))$("#language").value=lang;
  if($("#settingsLanguageSelect"))$("#settingsLanguageSelect").value=lang;
  if($("#settingsLanguage"))$("#settingsLanguage").textContent=`${user?.age?user.age+" • ":""}${["ar","en","fr","es","de","tr","it","ru","zh","ja","ko"].includes(lang)?({ar:"العربية",en:"English",fr:"Français",es:"Español",de:"Deutsch",tr:"Türkçe",it:"Italiano",ru:"Русский",zh:"中文",ja:"日本語",ko:"한국어"}[lang]):lang}`;
  renderPlaces("#featuredPlaces","all"); renderPlaces("#allPlaces",document.querySelector(".filter.active")?.dataset.filter||"all");
}

function showScreen(id){
  if(id==="home"&&!user) id="profile";
  $$(".screen").forEach(s=>s.classList.remove("active"));
  const target=$("#"+id); if(target) target.classList.add("active");
  $$(".nav").forEach(n=>n.classList.toggle("active",n.dataset.go===id));
  window.scrollTo({top:0,behavior:"smooth"});
}
function toast(msg){const t=$("#toast");if(!t)return;t.textContent=msg;t.classList.add("show");clearTimeout(window.__toast);window.__toast=setTimeout(()=>t.classList.remove("show"),2400)}

function renderPlaces(container,filter="all"){
  const el=$(container); if(!el)return;
  const list=filter==="all"?places:places.filter(p=>p.category===filter);
  el.innerHTML=list.map(p=>`<article class="place" data-place="${p.id}">
    <div class="place-info"><h4>${placeText(p,"name")} <span class="place-meta">${tr(p.category)}</span></h4><p>${placeText(p,"area")}</p>
    <div class="place-meta">★ ${p.rating} &nbsp; • &nbsp; ◷ ${placeText(p,"time")} &nbsp; • &nbsp; 📍 ${p.distance}</div>
    <button class="video-btn" data-place-name="${p.id}">🎥 ${tr("video")}</button></div><img src="${p.image}" alt="${placeText(p,"name")}" loading="lazy"></article>`).join("");
  el.querySelectorAll(".video-btn").forEach(b=>b.addEventListener("click",e=>{e.stopPropagation();openPlace(b.dataset.placeName)}));
  el.querySelectorAll(".place").forEach(c=>c.addEventListener("click",()=>openPlace(c.dataset.place)));
}

function openPlace(id){
  const p=places.find(x=>x.id===id); if(!p)return;
  $("#placeModalImage").src=p.image; $("#placeModalImage").alt=placeText(p,"name");
  $("#placeModalTitle").textContent=placeText(p,"name"); $("#placeModalArea").textContent=placeText(p,"area"); $("#placeModalCategory").textContent=tr(p.category);
  $("#placeModalMeta").innerHTML=`★ ${p.rating} &nbsp; • &nbsp; ◷ ${placeText(p,"time")} &nbsp; • &nbsp; 📍 ${p.distance}`;
  $("#placeVideos").innerHTML=p.videos.map((id,i)=>`<div class="video-card"><div class="video-label">${tr("video")} ${i+1}</div><iframe src="https://www.youtube.com/embed/${id}" title="${placeText(p,"name")} ${tr("video")} ${i+1}" loading="lazy" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe><a href="https://www.youtube.com/watch?v=${id}" target="_blank" rel="noopener">${tr("openYoutube")}</a></div>`).join("");
  $("#placeModal").classList.add("show"); $("#placeModal").setAttribute("aria-hidden","false");
}
function closePlace(){const m=$("#placeModal");if(m){m.classList.remove("show");m.setAttribute("aria-hidden","true")}if($("#placeVideos"))$("#placeVideos").innerHTML=""}

async function connectGlasses(){
  if(!("bluetooth" in navigator)){toast(tr("bluetoothUnavailable"));$("#connectionState").textContent=tr("demoConnected");return}
  try{
    bluetoothDevice=await navigator.bluetooth.requestDevice({acceptAllDevices:true,optionalServices:["battery_service"]});
    $("#connectionState").textContent=`${bluetoothDevice.name||"Daleel Glass One"} — ${tr("connected")}`;
    toast(tr("connected"));
    bluetoothDevice.addEventListener("gattserverdisconnected",()=>{$("#connectionState").textContent=tr("demoConnected")});
  }catch(e){ if(e.name!=="NotFoundError") console.warn(e); }
}

function locateMe(){
  if(!navigator.geolocation){toast(tr("locationDenied"));return}
  navigator.geolocation.getCurrentPosition(pos=>{toast(`${tr("locationFound")} • ${pos.coords.latitude.toFixed(4)}, ${pos.coords.longitude.toFixed(4)}`)},()=>toast(tr("locationDenied")),{enableHighAccuracy:true,timeout:10000});
}
function voiceGuide(){
  const text=lang==="ar"?"تابع إلى الأمام. تم تشغيل التوجيه التجريبي.":`${tr("voiceStarted")}. Follow the route ahead.`;
  if("speechSynthesis" in window){speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(text);u.lang={ar:"ar-JO",en:"en-US",fr:"fr-FR",es:"es-ES",de:"de-DE",tr:"tr-TR",it:"it-IT",ru:"ru-RU",zh:"zh-CN",ja:"ja-JP",ko:"ko-KR"}[lang];speechSynthesis.speak(u);}
  toast(tr("voiceStarted"));
}

$$("[data-go]").forEach(btn=>btn.addEventListener("click",()=>showScreen(btn.dataset.go)));
$$(".choice").forEach(btn=>btn.addEventListener("click",()=>{const group=btn.dataset.group;selected[group]=btn.dataset.value;$$(`.choice[data-group="${group}"]`).forEach(x=>x.classList.remove("selected"));btn.classList.add("selected")}));
$("#language")?.addEventListener("change",e=>{lang=e.target.value;selected.language=lang;localStorage.setItem("daleelLang",lang);applyLanguage()});
$("#settingsLanguageSelect")?.addEventListener("change",e=>{lang=e.target.value;selected.language=lang;localStorage.setItem("daleelLang",lang);if(user){user.language=lang;localStorage.setItem("daleelUser",JSON.stringify(user))}applyLanguage()});
$("#profileForm")?.addEventListener("submit",async e=>{
  e.preventDefault();
  user={name:$("#name").value.trim(),age:Number($("#age").value),gender:selected.gender||"private",language:lang};
  localStorage.setItem("daleelUser",JSON.stringify(user));
  $("#userName").textContent=user.name; $("#settingsName").textContent=user.name;
  if(firebaseReady){try{await addDoc(collection(db,"users"),{...user,createdAt:serverTimestamp()});toast(tr("saved"))}catch(err){console.error(err);toast(tr("savedLocal"))}}else toast(tr("savedLocal"));
  showScreen("home");
});
$$(".filter").forEach(btn=>btn.addEventListener("click",()=>{$$(".filter").forEach(x=>x.classList.remove("active"));btn.classList.add("active");renderPlaces("#allPlaces",btn.dataset.filter)}));
$("#connectGlasses")?.addEventListener("click",connectGlasses);
$("#locateMe")?.addEventListener("click",locateMe);
$("#voiceGuide")?.addEventListener("click",voiceGuide);
$("#placeModalClose")?.addEventListener("click",closePlace);
$("#placeModal")?.addEventListener("click",e=>{if(e.target.id==="placeModal")closePlace()});
document.addEventListener("keydown",e=>{if(e.key==="Escape")closePlace()});

if(user){$("#userName").textContent=user.name;$("#settingsName").textContent=user.name;lang=user.language||lang;selected.language=lang}
applyLanguage();
if(firebaseReady){try{onSnapshot(collection(db,"places"),snap=>{if(snap.size)console.log("Firebase places loaded:",snap.docs.map(d=>({id:d.id,...d.data()})))})}catch(e){console.warn("Firestore listener not active:",e)}}
